- development-updates.md
Adds a development update for week 1.
I'm open to having write permissions in this repo, so I can help with reviews and merging PRs too.
cc @JoshDavisLight
> dev update: jsign week 1

- program-guide/mentors.md
Add @michaelsproul and @paulhauner as mentors :heart: 
@michaelsproul could you please give me a thumbs up to indicate I have your consent :smile: :pray:
> Add Michael Sproul and Paul Hauner as mentors

- notes/amadia.md
> add: amadia update notes

- development-updates.md
Development updates for week 2.
> development-updates: jsign week 2

- development-updates.md
More research on light-client implementations and zero-knowledge. 
Have meeting this week with the Ultralight client implementation team for the Portal Network.
> add: amadia update 2

- development-updates.md
- notes/vidkersic.md
> add update 2

- development-updates.md
This pull request adds my first update:
https://hackmd.io/@geemo/Bkx7ev5Vs
> geemo update 1

- development-updates.md
Initial update for phase 1 of EPF
> Initial update for phase 1 of EPF

- development-updates.md
> jsign: update week 3

- development-updates.md
- notes/robzajac.md
Dev update for @robzajac in week 2.
> robzajac: Dev update week 2

- development-updates.md
Add link to my second development update
> Add Jimmy's development update #2

- program-guide/reading.md
One of the current recommendations is Vitalik's explanation of Ethereum back in Devcon1. I suggest adding Devcon6's version of this talk. It's basically the same, but it contains all the current features of the protocol.
> add Ethereum in 30 minutes by Vitalik (Devcon6) to suggested reading

- development-updates.md
> development-update: jsign update #4

- development-updates.md
- notes/brechy.md
> add: brechy's second update

- development-updates.md
> jsign: update 5

- development-updates.md
- notes/patstiles.md
My 2nd dev update, spent most of my time reading code than writing any but hey thats how it goes sometimes! Would appreciate any feedback!
> Dev Update 2

- notes/jayesh.md
- projects/4337-wallet.md
Hello, this is my first update!
- Communicated with Garvit and edited the 4337.md to match the project template layout
- Added personal updates and notes
> Update #1 - Jayesh

- projects/verkle-trie-migration-exploration.md
This PR contains the first version of my project.
> project: jsign project first version

- projects/model-danksharding.md
Rough draft is coming at ya now.  Currently iterating on my project proposal with Cayman. 
Reaching out to Dankrad for guidance after updating the proposal.
Will have a fleshed out project proposal by next week!
> Add rough draft project summary to projects folder

- development-updates.md
> jsign: update 6

- development-updates.md
add my updates for fellowship since start
> add my updates for fellowship

- development-updates.md
- notes/brechy.md
> add: third update

- development-updates.md
> jsign: update 7

- projects/4844-consensus-client.md
EIP-4844 project draft, co-authored by @0xGabi and @jimmygchen .
Will be reaching out to mentors in the next few days for feedback and updates.
> Add EIP-4844 consensus client project

- development-updates.md
My dev updates from this past week!
> Add Update 4

- development-updates.md
My updates this week: created project proposal for EIP-4844 work, and started planning our work on Builder API changes for EIP-4844, and continued work on interop testing.
> Add Jimmy's 5th update

- projects/model-das.md
Met with Eric and Timofey (Chainsafe DAS R&D) earlier this week.  
It turns out they have been working on pretty much exactly what I want to do for the Fellowship.  After meeting with and explaining my project idea to them, they provided a ton of feedback for how I should go about creating my project.
Here's the new project proposal!
> Add new Project Proposal

- development-updates.md
> development-updates: jsign update 8

- development-updates.md
> development-updates: jsign update 10

- development-updates.md
- notes/brechy.md
> add: brechy's update

- development-updates.md
A lot of focus has been on project execution this week, and we’ve made some really good progress!
This is the list of things I’ve worked on this week, and more details in the update:
- Add Lighthouse to eip-4844-interop repo
- Beacon API & Builder Spec updates for EIP-4844
- Implement builder updates in Lighthouse
- Some other small improvements on related projects
> Jimmy's #7 development update

- projects/validator-signing-key-revocation.md
> project-proposal-alpesh

- projects/helios-cl-p2p.md
> add: brechy's project proposal

- projects/eth-monitor.md
> Project proposal update - bem

- development-updates.md
Ethereum Protocol Fellowship 8th week update
> Ethereum Protocol Fellowship 8th week update

- development-updates.md
- notes/vidkersic.md
> dev update 6

- development-updates.md
Signed-off-by: Ignacio Hagopian <jsign.uy@gmail.com>
> development-updates: jsign 11

- development-updates.md
- notes/robzajac.md
> Week 10 update

- development-updates.md
Hi all, 
here' s my weekly update, I'm mostly working on Lighthouse and testing EIP-4844. I've added some notes on sending and downloading blobs via a new Beacon API.
https://hackmd.io/@jimmygchen/SJ21bsH9o
> Add Jimmy's #9 update (week 10)

- development-updates.md
Focusing on helpful P2P networking features of holepunch.io release that would be useful for Portal Network clients.
> 8th Development Update

- development-updates.md
> development-update: jsign 12

- development-updates.md
- notes/brechy.md
> add: brechy's 6th update

- development-updates.md
Here's my update: https://hackmd.io/@jimmygchen/ryyAai3qs
This week I've been focusing on implementing the builder changes for EIP-4844 in Lighthouse, and also proposed a PR in Beacon API spec to introduce a new getBlobs endpoint.
> Add Jimmy's #10 update

- development-updates.md
Adds development update number 2 for me Geemo.
> Add my 2nd update

- development-updates.md
https://hackmd.io/@wanningD/rJgrKsSii from Wanning Ding
> Ethereum Protocol Fellowship 12th week update

- development-updates.md
This week I've continued my work on builder updates, and mostly focused on updating the rust libraries with new Capella & Deneb types, and worked on a backfill sync issue in Lighthouse.
https://hackmd.io/@jimmygchen/HJodpkpcs
> Add Jimmy's #11 update

- development-updates.md
> devupdate: ignacio 13

- development-updates.md
Relatively short update this week due to public holiday here (🇦🇺 day), mainly focused on adding Capella & EIP-4844 types to Rust consensus & mev libraries and closing out my existing PRs:
https://hackmd.io/@jimmygchen/rJw2Zjl2j
> Add Jimmy's #12 update

- development-updates.md
- notes/brechy.md
> add: brechy's seventh update

- development-updates.md
> Geemo Update 3

- development-updates.md
This week I've mainly focused on implementation of rate-limiting backfill sync in Lighthouse, and monitoring the improvements in resource usage. My update here:
https://hackmd.io/@jimmygchen/ByQZvPZns
> Add Jimmy's #13 update

- development-updates.md
- notes/robzajac.md
> Dev update week 14

- development-updates.md
> development-updates: jsign update 14

- development-updates.md
Covers part of my recent research & development with a blazing fast Merkle tree implementation w/ tiny keccak & Rust
> Batch update

- development-updates.md
- notes/alpesh.md
I have updated the git to include hackmd page which includes all my weekly updates.
> project update - alpesh

- development-updates.md
This week I've been focusing on wrapping up the Lighthouse historical backfill rate-limiting changes, and plan to shift my focus back to EIP-4844 changes soon:
https://hackmd.io/@jimmygchen/S1XoOhJTs
> Add Jimmy's #14 update

- development-updates.md
- notes/robzajac.md
> Dev update week 15

- development-updates.md
- notes/robzajac.md
> Dev update week 16

- development-updates.md
> development-updates: jsign 15

- development-updates.md
Hi everyone, this week I worked on a few things: 
1. Wrapping up the backfill sync rate-limiting PR in Lighthouse.
2. Updated existing 4844 PRs (specs, Rust libraries) impacted by the blob decoupling and blob signing spec changes.
3. Implemented a draft version of blob signing endpoints and validator blob signing functionalities in Lighthouse.
More details here: https://hackmd.io/@jimmygchen/rJMB0nDpo
> Add Jimmy's #15 update

- projects/light-client-consensus-layer.md
A few edits to reflect updated roadmap
> Update project details

- development-updates.md
- notes/robzajac.md
My last dev update for EPF cohort three 🚀 🎉
> Final dev update

- development-updates.md
- notes/vidkersic.md
- projects/4337-bundler-rust.md
Some small changes to the project description and goals, roadmap updated to the current state.
Adding also link to final dev update.
> update project details and final dev update

- development-updates.md
- notes/brechy.md
- projects/helios-cl-p2p.md
> Update project proposal and add latest update

- development-updates.md
- projects/4844-consensus-client.md
Apologies for the delay - my final update here :) 
https://hackmd.io/@jimmygchen/Sy_Z5qj0j
> Jimmy's #16 final dev and project update
